exclude: ^(data|sprout)/

substitutions:
  - &exclude
    exclude: ^(cfme|scripts) # for now disable - we shall gradually reenable it
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.5
  hooks:
  - id: reorder-python-imports
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    args: [--safe, --line-length, '100']
    language_version: python3.6
    <<: *exclude
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
    exclude: ^(sprout|scripts|cfme/fixtures/rdb.py)
  - id: flake8
    language_version: python3.6
    <<: *exclude
# separately flake via system for polarion docstrings plugins
- repo: local
  hooks:
    - id: system-flake8
      name: flake8-plugins
      description: flake8 integration_tests plugins
      entry: python -m flake8.__main__ --select P --ignore P665
      files: \.py$
      language: system
- repo: https://github.com/asottile/pyupgrade
  rev: v1.10.1
  hooks:
  - id: pyupgrade
    language_version: python3.6
    <<: *exclude
