language: python
cache: pip
python:
  - '2.7'
  - '3.6'
env:
  #   work around travis being missconfigured
  - BOTO_CONFIG=/dev/null
install:
  - pip install -U setuptools pip
  - python -m cfme.scripting.quickstart
script:
- pytest cfme/utils/tests cfme/modeling/tests requirements  -v --dummy-appliance
- pytest -p no:cfme cfme/tests/test_modules_importable.py
- pytest -v --dummy-appliance --collectonly
after_success:
  - coveralls