language: python
python:
  - '2.7'
  - '3.6'
stages:
- linting
- test
- deploy

jobs:
  include:
    - stage: deploy
      python: '3.6'
      env:
      install: pip install -U setuptools setuptools_scm pbr
      script: skip
      deploy:
        provider: pypi
        user: missing
        password: ~
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        on:
          tags: true
          repo: ManageIQ/integration_tests
    - stage: linting
      python: '3.6'
      env:
      install:
      - pip install pre-commit
      - pre-commit install-hooks
      script:
      - pre-commit run --all-files
env:
  # work around travis being missconfigured
  - BOTO_CONFIG=/dev/null
install:
  - python -m cfme.scripting.quickstart
script:
- pytest cfme/utils/tests cfme/modeling/tests requirements  -v --dummy-appliance
- pytest -p no:cfme cfme/tests/test_modules_importable.py
- pytest -v --dummy-appliance --collectonly
after_success:
  - coveralls
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit